defaults:
  - model: qwen2_5_7b
  - data: ambignq
  - training: sft
  - evaluation: default
  - deployment: hf
  - _self_

seed: 42
model_name: "sft"
output_dir: "outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}"

publication_model: null
experiment: null
stage: null

# Global paths
project_dir: ${hydra:runtime.cwd}
data_dir: "${project_dir}/data"
models_dir: "${project_dir}/models"

# Weights & Biases Configuration
wandb:
  project: ${oc.env:WANDB_PROJECT,ask-before-answer}
  entity: ${oc.env:WANDB_ENTITY,rl4aa}
  registry_name: Model
  registry_collection: "AskBeforeAnswer-${publication_model}"
  registry_alias: production
